config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#canvas'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get'homes/canvas' => 'homes#canvas'
  get'homes/top' => 'homes#top'
  get'homes/advansed' => 'homes#advansed'
  get'homes/image' => 'homes#image'
  get'homes/magick'
  get'homes/index'
  
  resources :users, only:[:create, :index, :show]
  resources :post_images, only:[:create, :index, :show] do
    member do
      post :save
      post :download
      get :custome
      get :thumbnail
    end
  end 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  has_one_attached :base_image
  has_many_attached :images
  has_many_attached :thumbnails
  
  validates :name, :base_image, :images, presence: true
  
  def size
    self.images.count
  end 
  
  
  def make_thumbnail 
    
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  # validates(:name, {presence: true})と書くのと同じ。
  validates :name, presence: true
  has_one_attached :image
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg')
    end
    self.image
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def canvas
  end 
  
  def magick
    require 'mini_magick'
    # assetsから画像を呼び出す。
    # input_path = "rubyman_shibainu.png"
    # image = MiniMagick::Image.open(input_path)
    # image.resize "200x200"
    # image.write "rubyman_shibainu.png"
    # # disposition: "attachement"でダウンロードする。inlineはダウンロードせずに表示。
    # send_file "rubyman_shibainu.png", type: "image/png", disposition: "inline"
    # @magick = "rubyman_shibainu.png"
    
    # ユーザー画像をminimagickで加工処理。
    user_image = User.find(3).image
    image_blob = user_image.download
    image = MiniMagick::Image.read(image_blob)
    image.resize "100x100"
    send_data image.to_blob, type: "image/png", disposition: "inline"
    
  end
  
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  
  def index
    @post_images = PostImage.all
  end 
  
  def show
    @post_image = PostImage.find(params[:id])
    input_path = @post_image.images[1]
    # image = MiniMagick::Image.open(input_path)
    # @trimed_image = @post_image.images.trim_image
    @trimed_image = trim_image(input_path)
  end
  
  def create
    post_image = PostImage.new(post_image_params)
    post_image.user_id = 3
    
    # images = params[:post_image][:images]
    
    
    if post_image.save
      post_image.images.each do |img|
        downloaded_image = img.download
        image = MiniMagick::Image.read(downloaded_image)
        image.trim
        tmp_file = Tempfile.new(['trimmed_', ".#{image.type.downcase}"], 'tmp')
        image.write(tmp_file.path)
        tmp_file.rewind
        trimmed_blob = ActiveStorage::Blob.create_and_upload!(
          io: tmp_file,
          filename: "trimmed_#{img.filename}",
          content_type: image.mime_type
        )
        post_image.thumbnails.attach(trimmed_blob)
        tmp_file.close
        tmp_file.unlink
      end
      redirect_to post_images_path
    else
      @post_images = PostImage.all
      flash.now[:notice] = "失敗しました。"
      render :index
    end
  end 
  
  def save
    require "mini_magick"
    
    post_image = PostImage.find(params[:id])
    base_image = post_image.base_image
    base_image = base_image.download
    base_image = MiniMagick::Image.read(base_image)
    
    input_path = post_image.images[0]
    result = base_image.composite(MiniMagick::Image.open(input_path)) do |config|
      config.compose "Over"
      config.gravity "NorthWest"
      # 座標を動かせる。x, yの順。
      # config.geometry "+90+80"
    end 
    send_data result.to_blob, type: "image/png", disposition: "attachment; filename = fine.png"
  end 
  
  def download
    # post_image"=>{"images_d"=>["0", "1"]}
    require "mini_magick"
    which_images = params[:post_image][:images_d]
    # size = which_images.size
    
    post_image = PostImage.find(params[:id])
    base_image = post_image.base_image
    base_image = base_image.download
    base_image = MiniMagick::Image.read(base_image)
    
    which_images.each do |nth_image|
      input = post_image.images[nth_image.to_i]
      base_image = base_image.composite(MiniMagick::Image.open(input)) do |config|
        config.compose "Over"
        config.gravity "NorthWest"
      end 
    end
    # これだと前から順番に取得してしまう。
    # for i in 0..size - 1 do
    #   input = post_image.images[i]
    #   base_image = base_image.composite(MiniMagick::Image.open(input)) do |config|
    #     config.compose "Over"
    #     config.gravity "NorthWest"
    #   end 
    # end 
    result = base_image
    send_data result.to_blob, type: "image/png", disposition: "attachment; filename = fine.png"
  end 
  
  def custome
    @post_image = PostImage.find(params[:id])
    @size = @post_image.size - 1
  end
  
  def thumbnail
    @post_image = PostImage.find(params[:id])
    @size = @post_image.size - 1
    # input = @post_image.images[0]
    # images = trim_image(input)
    # @post_image.images.each do |image|
    #   images = images + trim_image(image)
    # end 
    # @trimmed_images = images
  end
  
  private
  
  def post_image_params
    params.require(:post_image).permit(:name, :base_image, images: [])
  end 
  
  def trim_image(attachment)
    # Active Storageの添付ファイルからMiniMagick::Imageオブジェクトを生成
    image = MiniMagick::Image.read(attachment.download)
    
    # 画像をトリミング
    image.trim
    
    # トリミングされた画像を一時ファイルに保存
    # "trimmed_"で始まり、拡張子は元の画像の拡張子と同じになる一時ファイルを生成する。
    tmp_file = Tempfile.new(['trimmed_', ".#{image.type.downcase}"], 'tmp')
    # MiniMagick::Imageオブジェクトで処理された(ここではトリム)画像を一時ファイルに書き込む
    image.write(tmp_file.path)
    tmp_file.rewind
  
    # 一時ファイルをActiveStorageにアタッチ。
    # MiniMagickで加工した画像をそのままviewで表示することはできないため、active_storageに保存する。
    trimmed_blob = ActiveStorage::Blob.create_and_upload!(
      io: tmp_file,
      filename: "trimmed_#{attachment.filename}",
      content_type: image.mime_type
    )
  
    # 一時ファイルをクローズ。一時ファイルは消すとリソースが解放される。
    tmp_file.close
    tmp_file.unlink
  
    return trimmed_blob
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    # 変数に画像を入れることもできる！
    @image = "rubyman_shibainu.png"
    @users = User.all
    
    file_path = Rails.root.join('app/assets/images/rubyman_shibainu.png')
    image_magick = MiniMagick::Image.open(file_path)
    image_magick.resize("100x100")
    @image_magick = image_magick
    
    @user_image = User.find(3).image
  end 
  
  def show 
      
  end 
  
  def create
    User.create(user_params)
    redirect_to users_path
  end 
  
  private
  
  def user_params
    params.require(:user).permit(:name, :image)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/advansed.html.erb
<h1>advansed</h1>
<canvas id="canvas"></canvas>

app/views/homes/canvas.html.erb
<div class="container bg-light">
  <div class="row justify-content-center">
    <div class="col-ex-10 col-md-10 ">
      <canvas class="" id="paper"></canvas>
      <p class="bg-info" id="test">キャンバス↑</p>
      <button class="btn btn-info move-btn" id="test-btn">ボタン</button>
      <div class="abs">
        <div class="mt-3" id="moving-box"></div>
        <p id="moving-text" class="text-dark">右から左へ受け流す</p>
      </div>
      
    </div>
  </div>
</div>

app/views/homes/image.html.erb
<canvas class="mt-5 ml-3" id="canvas-image"></canvas>
<div id="can-ruby"><%= image_tag "ruby.png" %></div> 

app/views/homes/index.html.erb
<%= render 'layouts/frame', title: "homes_index" do %>
  <ul>
    <!--cssでなんとかする-->
    <li><%= link_to "post_image_index", post_images_path %></li>
    <li><%= link_to "usres_index", users_path %></li>
  </ul>
<% end %>

app/views/homes/magick.html.erb
<%= render 'layouts/frame', title: "magick" do %>
  <%= image_tag @magick %>
<% end %>

app/views/homes/top.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-3 col-md-4 col-sm-8">
      <h1 class="jquery">hello world!</h1>
      <!--<div>-->
        <%= image_tag 'sheep.png', class: "position-relative" %>
        
        <span id="ruby" class="inactive" style="display:none">
          <%= image_tag 'ruby.png', class: "position-absolute", style: "left: 15px;" %>
        </span>
        
        <span id="santa_hat" style="display:none">
          <%= image_tag 'Santa hat.png', class: "position-absolute", style: "left: 15px;" %>
        </span>
        
        <span id="necktie" style="display:none">
          <%= image_tag 'necktie.png', class: "position-absolute", style: "left: 15px;" %>
        </span>
        
        <span id="sunglasses" style="display:none">
          <%= image_tag 'sunglasses.png', class: "position-absolute", style: "left: 15px;" %>
        </span>
        
        
      <!--</div>-->
    </div>
    <div class="col-md-2 col-sm-4 mt-5">
      <button type="button" class="ruby-btn btn btn-danger mt-3">ルビー</button>
      <button type="button" class="santa_hat-btn btn btn-danger mt-3">サンタ帽子</button>
      <button type="button" class="necktie-btn btn btn-danger mt-3">ネクタイ</button>
      <button type="button" class="sunglasses-btn btn btn-danger mt-3">サングラス</button>
    </div>
    
    <!--<div class="box1"></div>-->
    <section>
      <div>
        <%= image_tag "normal_shibainu.png" %>
      </div>
      <input type="range" id="range">
    </section>
    
    <section class="col-12 sec-3">
      <div id="arrow1" class="arrow "></div>
      <div id="arrow2" class="arrow "></div>
    </section>
    
    <section class="sec-4">
      <canvas id="paper">
        
      </canvas>
    </section>
  </div>
</div>

<script>
  
  // document.getElementsByClassName('element').style.display = "none";
</script>

app/views/layouts/_flash.html.erb
<div>
  <% if flash.present? %>
    メッセージ[<%= flash[:notice] %>]
  <% end %>
</div>

app/views/layouts/_frame.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mb-3">
      <%= title %>ページです。
    </div>
    <div class="col mx-auto mt-3 mb-5">
      <%= yield %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="row justify-content-center no-gutters" style="height: 50px; background-color: #aaaaaa">
  <div class="col-10">
    <%= link_to "index", homes_index_path, class:"pl-5 text-light" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #555555; color: #ffffff; ">
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/post_images/custome.html.erb
<%= render 'layouts/frame', title: "custome" do %>
  <%= link_to "戻る", post_image_path(@post_image), class:"text-light mb-3" %><br>
  
  <!--実際に画像が動くところ-->
  <!--変数名はimage_numよりもnth_imageのほうがいいね-->
  <div class="position-relative">
    <%= image_tag @post_image.base_image, class:"position-absolute a", style:"z-index: -1" %>
    <% for image_num in 0..@size do %>
      <span class="image_<%= image_num %>" style="display: none">
        <%= image_tag @post_image.images[image_num], class:"position-absolute" %>
      </span>
    <% end %>
  </div>
  
  <!--スペース用の空div-->
  <div style="height: 200px"></div>
  <div>
   <!--チェックボックスで選択した画像の合成-->
  <%= form_with model: @post_image, url: download_post_image_path, method: :post do |f| %>
    <% for cnum in 0..@size do %>
      <%= f.check_box :images_d, { multiple: true }, cnum, nil %>
      <%= f.label :"images_d_#{cnum}", class:"images_d_#{cnum}" do %>
        <%= image_tag @post_image.images[cnum] %>
      <% end %>
    <% end %>
    <br>
    <%= f.submit 'チェックボックスで選択した画像の合成' %>
  <% end %>
  </div>
  
  <button class="button">ボタン</button>
  
<% end %>

<script>
  // チェックボックスをクリックして画像の表示、非表示
  let size = "<%= @size %>";
  $(document).ready(function(){
    
    for (let i = 0; i <= size; i++){
      $('.button').on('click', function(){
        console.log('button clicked!');
      })
      $('.images_d_' + i ).on('click', function(){
        console.log(i + 'button clicked!');
      $('.image_' + i ).toggle();
      })
    }
  })
</script>

app/views/post_images/index.html.erb
<%= render "layouts/frame", title: "post_image_index" do %>
  
  <%= form_with model: PostImage.new do |f| %>
    <div>
      <%= f.label :name, "タイトル" %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :base_image, "ベース画像" %>
      <%= f.file_field :base_image, accept: "image/*" %>
    </div>
    <div>
      <%= f.label :images, "付属画像" %>
      <%= f.file_field :images, multiple: true, accept: "image/*" %>
    </div>
    
    <%= f.submit "画像を登録" %>
  <% end %>
  
  <table class="table">
    <tbody>
      <% @post_images.each do |post_image| %>
        <tr>
          <td>
            <%= link_to post_image_path(post_image), class:"text-light"  do %>
              <%= post_image.name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td style="width: 250px;">
            <% if post_image.base_image.present? %>
              <%= image_tag post_image.base_image, size:"100x100" %>
            <% end %>  
          </td>
          <% post_image.images.each do |image| %>
            <td><%= image_tag image.variant(resize: '50x50') %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  
<% end %>

app/views/post_images/save.html.erb
<script>
  if (window.performance) {
    if (window.performance.navigation.type === 1) {
      alert("リロードされました");
      // window.location.href = 'back'
    }
  }
</script>

app/views/post_images/show.html.erb
<%= render 'layouts/frame', title: "post_image_show" do %>
  <%= link_to "戻る", post_images_path, class:"text-light" %>
  <%= link_to "カスタム", custome_post_image_path, class:"text-light" %>
  <%= link_to "サムネイル", thumbnail_post_image_path, class:"text-light" %>
  <div class="mt-3">
    <% if @post_image.base_image.present? %>
      <%= image_tag @post_image.base_image %>
    <% end %> 
    
    <% @post_image.images.each do |image| %>
      <span><%= image_tag image %></span>
    <% end %>
  </div>
  <div id="download">
    <%= link_to "Download", save_post_image_path, method: :post, class:"text-light" %>
  </div>
  
  <!--each分を使った画像のチェックボックス化-->
  <%= form_with model: @post_image do |f| %>
    <div>
      <% f.radio_button :images, 0 %>
      <%= f.label :images_0 do %>
        <%= image_tag @post_image.images[0] %>
      <% end %>
    </div>
    <%= f.submit "チェックボックスの情報を送る" %>
  <% end %>
  
  <!--for文を使った画像の表示-->
  <% size = @post_image.images.count %>
  <% for num in 0..size - 1 do %>
    <%= image_tag @post_image.images[num] %>
  <% end %>
  
  <!--for文を使った画像のラジオボックス化-->
  <%= form_with model: @post_image do |f| %>
    <% for num in 0..size -1 do %>
      <%= f.radio_button :images, num %>
      <%= f.label :"images_#{num}" do %>
        <%= image_tag @post_image.images[num] %>
      <% end %>
    <% end %>
    <%= f.submit 'ラジオボックスの情報を送る' %>
  <% end %>
  
  <!--for文を使った画像のチェックボックス化-->
  <%= form_with model: @post_image do |f| %>
    <% for cnum in 0..size -1 do %>
    <!--カラム名がradio_buttonと同じだと、check_boxを選択してもradioが選択されてしまうので、"_c"を追加。-->
      <%= f.check_box :images_c, { multiple: true }, cnum, nil %>
      <%= f.label :"images_c_#{cnum}" do %>
        <%= image_tag @post_image.images[cnum] %>
      <% end %>
    <% end %>
    <%= f.submit 'チェックボックスの情報を送る' %>
  <% end %>
  
   <!--チェックボックスで選択した画像の合成-->
  <%= form_with model: @post_image, url: download_post_image_path, method: :post do |f| %>
    <% for cnum in 0..size -1 do %>
      <%= f.check_box :images_d, { multiple: true }, cnum, nil %>
      <%= f.label :"images_d_#{cnum}" do %>
        <%= image_tag @post_image.images[cnum] %>
      <% end %>
    <% end %>
    <%= f.submit 'チェックボックスで選択した画像の合成' %>
  <% end %>
  
  <%= image_tag @trimed_image  %>
  
<% end %>

app/views/post_images/thumbnail.html.erb
<%= render 'layouts/frame', title: "thumbnail" do %>
  <%= link_to "戻る", post_image_path(@post_image), class:"text-light mb-3" %><br>
  
  <!--実際に画像が動くところ-->
  <!--変数名はimage_numよりもnth_imageのほうがいいね-->
  <div class="position-relative">
    <%= image_tag @post_image.base_image, class:"position-absolute a", style:"z-index: -1" %>
    <% for image_num in 0..@size do %>
      <span class="image_<%= image_num %>" style="display: none">
        <%= image_tag @post_image.images[image_num], class:"position-absolute" %>
      </span>
    <% end %>
  </div>
  
  <!--スペース用の空div-->
  <div style="height: 200px"></div>
  <div>
   <!--チェックボックスで選択した画像の合成-->
  <%= form_with model: @post_image, url: download_post_image_path, method: :post do |f| %>
    <% for cnum in 0..@size do %>
      <%= f.check_box :images_d, { multiple: true }, cnum, nil %>
      <%= f.label :"images_d_#{cnum}", class:"images_d_#{cnum}" do %>
        <%= image_tag @post_image.thumbnails[cnum] %>
      <% end %>
    <% end %>
    <br>
    <%= f.submit 'チェックボックスで選択した画像の合成' %>
  <% end %>
  </div>
  
<% end %>

<script>
  // チェックボックスをクリックして画像の表示、非表示
  let size = "<%= @size %>";
  $(document).ready(function(){
    
    for (let i = 0; i <= size; i++){
      $('.button').on('click', function(){
        console.log('button clicked!');
      })
      $('.images_d_' + i ).on('click', function(){
        console.log(i + 'button clicked!');
      $('.image_' + i ).toggle();
      })
    }
  })
</script>

app/views/users/index.html.erb
<%= render "layouts/frame", title: "index" do %>

  index page
  <%= image_tag "rubyman_shibainu.png" %>
  <%= image_tag @image %>
  <%= image_tag @image, size:("100x100") %>
  <!--↓変数に入れた画像に対してvariantは使えない-->
  <!--%= image_tag @image.variant(resize:'100x100') %>-->
  <%= p @image_magick %>
  <%= p @image_magick.path %>
  <!--各種情報呼び出し。何に使えるのか？-->-->
  <!--%= p @image_magick.details %>--><br>
  <%= @image_magick.write @image %><br>
  <%= @image_magick.write @image %>
  <%= image_tag @user_image %>
  
  <!--登録-->
  <%= form_with model: User.new do |f| %>
    <div>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.file_field :image, accept: "image/*" %>
    </div>
    <div class="checkbox">
      
    </div>
    <div>
      %= f.submit "ユーザーを保存" %>
    </div>
    
    
    
  <% end %>
  
  <table class="table">
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %><%= user.id %></td>
          <td><%= image_tag user.get_image.variant(resize:"100x100").processed %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  
  
<% end %>

app/views/users/show.html.erb
<%= render "layouts/frame" %>
<% provide(:title, "show") %>

<div class="container">
  <div class="row">
    <div class="col-auto">
      <p>show</p>
    </div>
    <div class="col mx-auto">
      <%= yield %>
    </div>
  </div>
</div>